export const contentBasedOnRole: Record<string, string> = {
  doctor: `
                        Doctors in hospital and emergency settings hold the responsibility of making rapid, evidence-based assessments when patients arrive with breathing difficulties. The very first step in a patient with chest pain or shortness of breath is to <span style="color: yellow; font-weight: 700;">take vital signs and a focused history</span>. This includes not only documenting symptoms like <span style="color: yellow; font-weight: 700;">difficulty breathing</span> but also asking about risk factors such as smoking, asthma, allergies, or prior cardiac disease. Beyond this, physical examination should include looking for <span style="color: yellow; font-weight: 700;">use of accessory muscles</span>, changes in skin color, and altered mental status.  
                        Diagnostic tests must be ordered quickly to guide management. A <span style="color: yellow; font-weight: 700;">chest X-ray</span> can detect pneumonia, pneumothorax, or pulmonary edema, while arterial blood gases reveal hypoxemia or hypercapnia. <span style="color: yellow; font-weight: 700;">Auscultation</span> allows doctors to <span style="color: yellow; font-weight: 700;">listen for abnormal lung sounds</span>, such as wheezes in asthma or crackles in fluid overload.  
                        Emergency protocols are always structured. In <span style="color: yellow; font-weight: 700;">Basic Life Support (BLS)</span>, doctors first <span style="color: yellow; font-weight: 700;">check the scene for safety</span> before approaching the patient. If breathing is inadequate, immediate airway interventions are considered. A central parameter to monitor is <span style="color: yellow; font-weight: 700;">oxygen saturation</span>; healthy adults remain at <span style="color: yellow; font-weight: 700;">95–100%</span>, and values lower than this require escalation.  
                        Life-threatening conditions must be recognized. In <span style="color: yellow; font-weight: 700;">anaphylaxis</span>, rapid <span style="color: yellow; font-weight: 700;">airway management</span> and epinephrine are lifesaving. In acute asthma attacks, <span style="color: yellow; font-weight: 700;">Salbutamol</span> is the first-line bronchodilator, while cyanosis—<span style="color: yellow; font-weight: 700;">blue lips or fingertips</span>—is an urgent warning of <span style="color: yellow; font-weight: 700;">hypoxia</span>.  
                        In modern practice, doctors must also consider differential diagnoses like pulmonary embolism or severe COVID-19 pneumonia. Escalating treatment from simple nasal cannula to <span style="color: yellow; font-weight: 700;">supplemental oxygen</span>, high-flow devices, or non-invasive ventilation is guided by continuous reassessment of airway, breathing, circulation, and mental status. The ability to make fast, structured decisions directly affects patient survival.  
  `,
  nurse: `
                        Nurses form the frontline of patient monitoring and provide rapid support when respiratory distress is suspected. Their role starts by carefully observing for <span style="color: yellow; font-weight: 700;">signs of respiratory distress</span> such as tachypnea, anxiety, or <span style="color: yellow; font-weight: 700;">cyanosis</span>. When these appear, the nurse must <span style="color: yellow; font-weight: 700;">inform the doctor immediately</span> while simultaneously preparing interventions.  
                        Before administering <span style="color: yellow; font-weight: 700;">oxygen therapy</span>, nurses check the <span style="color: yellow; font-weight: 700;">flow rate and equipment</span>—ensuring the tubing is not kinked, the humidifier bottle is filled if ordered, and the mask is intact. Positioning the patient in <span style="color: yellow; font-weight: 700;">Semi-Fowler’s</span> position improves comfort and oxygenation.  
                        Ongoing monitoring is critical. Nurses use pulse oximeters to detect <span style="color: yellow; font-weight: 700;">early hypoxia</span> and confirm that respiratory rates remain between <span style="color: yellow; font-weight: 700;">12–20 breaths per minute</span>. They also track heart rate, blood pressure, and mental status, documenting each change in the chart.  
                        Safety is always a concern. Oxygen is a powerful oxidizer and faulty equipment may create a <span style="color: yellow; font-weight: 700;">fire hazard</span>. Family members must be reminded not to smoke near oxygen devices. If a patient removes their oxygen mask, the nurse should <span style="color: yellow; font-weight: 700;">encourage and assist them to wear it properly</span> and explain its importance.  
                        Beyond immediate treatment, nurses help prevent long-term complications. They promote <span style="color: yellow; font-weight: 700;">deep breathing and coughing exercises</span>, use incentive spirometry, and mobilize patients to reduce the risk of pneumonia. After oxygen is given, nurses must document the <span style="color: yellow; font-weight: 700;">type of device, flow rate, and patient’s response</span>. If deterioration continues—especially with <span style="color: yellow; font-weight: 700;">cyanosis</span> or falling oxygen levels—the nurse escalates immediately for advanced support. Their vigilance often makes the difference between early stabilization and rapid decline.  
  `,
  respiratory_therapist: `
                        Respiratory therapists focus exclusively on airway and breathing, making their input vital during emergencies. When hypoxemia is severe, a <span style="color: yellow; font-weight: 700;">Non-rebreather mask</span> is often applied because it delivers <span style="color: yellow; font-weight: 700;">high-concentration oxygen</span> quickly. For obstructive conditions like asthma or COPD, therapists measure airflow with a <span style="color: yellow; font-weight: 700;">peak flow meter</span> to evaluate <span style="color: yellow; font-weight: 700;">lung strength and airflow</span>.  
                        If the airway collapses, <span style="color: yellow; font-weight: 700;">Continuous Positive Airway Pressure (CPAP)</span> is used to maintain airway patency and increase alveolar recruitment. During asthma attacks, <span style="color: yellow; font-weight: 700;">bronchodilator therapy</span>—typically <span style="color: yellow; font-weight: 700;">Salbutamol</span>—helps to <span style="color: yellow; font-weight: 700;">dilate airways and improve breathing</span>.  
                        In mechanically ventilated patients, therapists must troubleshoot rapidly. A sudden fall in oxygenation can point to a <span style="color: yellow; font-weight: 700;">leak or disconnection in the circuit</span>, but may also suggest pneumothorax or mucus plugging. Spirometry testing remains the gold standard in stable patients to evaluate <span style="color: yellow; font-weight: 700;">lung function</span>.  
                        <span style="color: yellow; font-weight: 700;">Auscultation</span> is part of every assessment. When <span style="color: yellow; font-weight: 700;">wheezing</span> is heard, it strongly indicates <span style="color: yellow; font-weight: 700;">airway obstruction or narrowing</span>. In contrast, crackles may signal pulmonary edema. Therapists also look for <span style="color: yellow; font-weight: 700;">chest muscle retractions</span>, which suggest that the patient is exhausting their respiratory reserves.  
                        To protect airways, oxygen at high flow rates should be humidified, maintaining mucosal comfort and preventing secretion drying. Advanced modalities, such as high-flow nasal cannula (HFNC) or non-invasive ventilation (NIV), are increasingly used to delay intubation and improve patient outcomes. Respiratory therapists balance technology with bedside assessment, ensuring each intervention supports both oxygenation and patient safety.  
  `,
  paramedic: `
                        Paramedics respond in unpredictable environments, from road traffic accidents to home emergencies, where rapid recognition and intervention save lives. On arrival, they always <span style="color: yellow; font-weight: 700;">check scene safety</span> before approaching the patient. The primary survey follows the ABCDE model: <span style="color: yellow; font-weight: 700;">Airway, Breathing, Circulation, Disability, Exposure</span>.  
                        Airway management is often the first priority. Tools such as a <span style="color: yellow; font-weight: 700;">bag-valve mask</span> provide immediate ventilation when a patient cannot breathe effectively. <span style="color: yellow; font-weight: 700;">Accessory muscle use</span>, tachypnea, or inability to speak in full sentences signal severe distress.  
                        Certain emergencies demand fast action. In <span style="color: yellow; font-weight: 700;">anaphylaxis</span>, administering <span style="color: yellow; font-weight: 700;">Adrenaline (epinephrine)</span> can reverse airway swelling. If <span style="color: yellow; font-weight: 700;">cyanosis</span> appears, paramedics know <span style="color: yellow; font-weight: 700;">oxygen deficiency</span> is worsening. For unconscious patients, the <span style="color: yellow; font-weight: 700;">head-tilt chin-lift</span> or jaw thrust is applied depending on spinal considerations.  
                        High-flow oxygen is commonly given through a <span style="color: yellow; font-weight: 700;">Non-rebreather mask</span>, while CPR is delivered at a <span style="color: yellow; font-weight: 700;">30:2 compression-to-ventilation ratio</span> when no advanced airway is in place. Paramedics also use pulse oximetry and, when available, capnography to guide care.  
                        Transport itself is therapeutic. Patients are positioned <span style="color: yellow; font-weight: 700;">sitting upright</span> to reduce work of breathing. Paramedics continuously reassess and communicate with receiving hospitals, relaying vital signs, interventions, and responses. They must manage both medical and trauma-related breathing problems, such as tension pneumothorax, for which rapid decompression can be lifesaving. Their ability to improvise, stabilize, and transport safely bridges the gap between the scene and definitive hospital care.  
  `,
  medical_student: `
                        Medical students are introduced early to the basics of recognizing and responding to respiratory emergencies. They learn that a healthy adult should breathe at a <span style="color: yellow; font-weight: 700;">rate of 12–20 breaths per minute</span>. Deviations, whether too fast or too slow, may signal pathology. <span style="color: yellow; font-weight: 700;">Asthma</span> is a common cause of respiratory distress, caused by airway inflammation and narrowing.  
                        A visible clue of poor oxygenation is <span style="color: yellow; font-weight: 700;">cyanosis</span>, which indicates <span style="color: yellow; font-weight: 700;">decreased oxygen in the blood</span>. Students learn to use a <span style="color: yellow; font-weight: 700;">pulse oximeter</span> to check oxygen saturation and correlate it with physical signs. During auscultation, hearing <span style="color: yellow; font-weight: 700;">wheezing</span> often points toward <span style="color: yellow; font-weight: 700;">asthma</span> or airway obstruction.  
                        Not all symptoms are relevant. For example, <span style="color: yellow; font-weight: 700;">slow digestion</span> is not considered a feature of respiratory distress. Instead, learners are taught to focus on breathing effort, rate, sounds, and oxygen levels.  
                        Choking emergencies are emphasized in training. If a patient <span style="color: yellow; font-weight: 700;">cannot speak</span> due to airway obstruction, the <span style="color: yellow; font-weight: 700;">Heimlich maneuver</span> should be performed while summoning help. For those with difficulty breathing but an open airway, patients are best positioned <span style="color: yellow; font-weight: 700;">sitting upright</span> to ease ventilation.  
                        Students also practice basic oxygen therapy. The goal of <span style="color: yellow; font-weight: 700;">oxygen administration</span> is to <span style="color: yellow; font-weight: 700;">increase oxygen levels</span> and relieve hypoxia. Emergency responses always follow the <span style="color: yellow; font-weight: 700;">ABC approach</span>: secure the <span style="color: yellow; font-weight: 700;">Airway</span>, then assess Breathing and Circulation. Building familiarity with this structured approach prepares students to escalate appropriately and support senior clinicians during critical events.  
  `
};
